<template>
	<div class="loader">
		<svg
			class="h-14 w-14"
			xmlns="http://www.w3.org/2000/svg"
			xmlns:xlink="http://www.w3.org/1999/xlink"
			style=" background: none; display: block; shape-rendering: auto;"
			viewBox="0 0 100 100"
			preserveAspectRatio="xMidYMid"
		>
			<circle
				cx="50"
				cy="50"
				fill="none"
				stroke="#b9b9b9"
				stroke-width="9"
				r="29"
				stroke-dasharray="136.659280431156 47.553093477052"
			>
				<animateTransform
					attributeName="transform"
					type="rotate"
					repeatCount="indefinite"
					dur="2.0408163265306123s"
					values="0 50 50;360 50 50"
					keyTimes="0;1"
				></animateTransform>
			</circle>
			<!-- [ldio] generated by https://loading.io/ -->
		</svg>
	</div>
</template>

<script>
	export default {};
</script>

<style lang="scss" scoped>
	.loader {
		min-height: 100vh;
		display: flex;
		align-items: start;
		justify-content: center;
		padding-top: 30%;
	}
</style>
